### ISSUE TITLE
Lizenzprobleme mit Arial-Font

### ISSUE THREAD

**Issue by The-Compiler** [ost-fh/Latex-Beamer-Theme#4]
Das Template nutzt ja die Arial-Font und sagt explizit:

> Die definierten Fonts und Farben entsprechen dem Corporate Design und sollten nicht editiert werden.

Das sehe ich als recht problematisch an. Die Lizenz der Arial-Schrift sagt relativ klar, dass ich sie auf meinem Linux nicht verwenden darf:

> Microsoft supplied font. You may use this font to create, display, and print content as permitted by the license terms or terms of use, of the Microsoft product, service, or content in which this font was included. You may only (i) embed this font in content as permitted by the embedding restrictions included in this font; and (ii) temporarily download this font to a printer or other output device to help print content. Any other use is prohibited.

Siehe auch die [Font redistribution FAQ](https://docs.microsoft.com/en-us/typography/fonts/font-faq) dazu.

Ich wage mal zu behaupten, dass das keine explizit ausgewählte Schrift war, nachdem's ja soweit ich weiss die Standardschrift von Powerpoint ist. Eine Möglichkeit wäre dann vermutlich, sie durch eine offene aber ähnliche Schrift (z.B. [Liberation Sans](https://en.wikipedia.org/wiki/Liberation_fonts)) zu ersetzen.

Wie sieht/handhabt ihr das?

**Comment by misto** [comment]
Doch das ist schon explizit im Corporate Design so festgelegt, war auch schon in der HSR so. Ich muss zugeben, dass ich das Template unter macOS nutze, aber @stefan-ka verwendet es unter Linux.

**Comment by stefan-ka** [comment]
Ich habe bis anhin [ttf-mscorefonts-installer](https://pkgs.org/download/ttf-mscorefonts-installer) verwendet um Arial zu installieren. Wie [hier beschrieben](https://itsfoss.com/install-microsoft-fonts-ubuntu/) muss man bei der Installation der Microsoft EULA zustimmen, und kann die Schriften dann verwenden.

Vermutlich wäre es aber einfacher/besser, einfach die [Liberation fonts](https://en.wikipedia.org/wiki/Liberation_fonts) zu verwenden, ja. Da gibts Lizenz-technisch sicher kein Problem und die wurden von Red Hat explizit dafür entwickelt Schriften wie Arial zu substituieren.

**Comment by misto** [comment]
Könntest du das im README vielleicht kurz beschreiben? Den Default möchte ich schon bei Arial lassen.

**Comment by The-Compiler** [comment]
Ich *kann* die Arial-Font durchaus schon installieren/verwenden, aber man verstösst dabei halt gegen die EULA, die man eben gerade akzeptiert hatte :wink: Der Pragmatiker in mir hat da auch kein Problem damit, aber ich würd halt trotzdem gerne ermöglichen, dass Linux-User das Theme nutzen können, ohne MS-Fonts installieren zu müssen bzw. gegen Lizenzbestimmungen verstossen zu müssen :slightly_smiling_face: 

Hier ein Vergleich zwischen Libration Sans (links) und Arial (rechts):

![image](https://user-images.githubusercontent.com/625793/93024083-d81f2800-f5f3-11ea-8b30-41ead8653a62.png)

Viel Unterschied sieht man effektiv nicht. Das erste was mir auffiel ist das "ö" in "können", aber da muss man schon sehr genau hinschauen.

Was hält ihr davon, Arial zu nehmen aber automatisch einen Fallback auf Liberation Sans zu machen, falls Arial nicht gefunden wird? Ev. passiert das sogar schon automatisch (je nachdem wie sich Liberation Sans genau einnistet), aber falls nicht scheints ein `\IfFontExistsTF` in `fontspec` zu geben:

![image](https://user-images.githubusercontent.com/625793/93024138-65627c80-f5f4-11ea-9986-ac5a614f830f.png)

Ich würd mir das sonst die nächsten Tage mal anschauen, falls das nicht automatisch passiert und das für euch so okay ist. Dann müssen die Leute nicht von Hand am Theme rumbasteln.

**Comment by das-g** [comment]
> Was hält ihr davon, Arial zu nehmen aber automatisch einen Fallback auf Liberation Sans zu machen, falls Arial nicht gefunden wird?

:+1: Gute Idee!

> Ev. passiert das sogar schon automatisch (je nachdem wie sich Liberation Sans genau einnistet), [...]

Selbst wenn das auf manches Systemen der Fall wäre (was erst zu überprüfen wäre) ist ein explizit im Theme angegebener Fallback vermutlich portabler. Ich weiss nicht, wie die Font-Fallback-Kaskaden für welche Software wie funktionieren, kann mir aber gut vorstellen, dass sie Betriebssystem- und Distro-abhängigist.

Wäre es sinnvoll, beim [Upstream](https://intranet.rj.ost.ch/kommunikation/corporate-design/vorlagen/) nachzufragen, welche Schriftart(en) als Fallback präferiert wird/werden, wenn/wo Arial nicht legal genutzt werden kann? Ich vermute, dass die Lizenz-/EULA-Problematik dort bislang gar nicht bewusst ist.

**Comment by The-Compiler** [comment]
> Wäre es sinnvoll, beim [Upstream](https://intranet.rj.ost.ch/kommunikation/corporate-design/vorlagen/) nachzufragen, welche Schriftart(en) als Fallback präferiert wird/werden, wenn/wo Arial nicht legal genutzt werden kann? Ich vermute, dass die Lizenz-/EULA-Problematik dort bislang gar nicht bewusst ist.

Kann man schon machen, sofern @misto oder @stefan-ka das nicht eh schon gemacht haben. Ich weiss aber nicht, inwiefern da Alternativen wie z.B. eben Liberation Sans überhaupt bekannt sind. Ich vermute, es heisst dann einfach "nein, Arial darf auf keinen Fall ersetzt werden", aber vielleicht täusche ich mich da ja :wink:

**Comment by stefan-ka** [comment]
Habe meinerseits keine solchen Abklärungen getroffen... (@misto vielleicht?) Habe schnell eine Lösung gebraucht und entsprechend pragmatisch gehandelt :) (habe morgen Präsentation an Konferenz; die sollen froh sein dass ich überhaupt das OST-Template dafür verwende :) 
Dabei ist mir vieles lieber als MS Powerpoint verwenden zu müssen.

Fallback implementieren finde ich aber gute Idee 👍 Wenns da optisch keinen grossen Unterschied gibt, würde ich das einfach verwenden... (glaube nicht daran dass der Upstream innert nützlicher Frist eine Lösung präsentieren wird)

**Comment by misto** [comment]
Sehe das wie Stefan.. ist ja nur ein Fallback, und ich glaube nicht, dass sich das schon jemand überlegt hat und eine Alternative definiert wurde.

**Comment by das-g** [comment]
Versteht mich nicht falsch: Den Fallback können wir ruhig unabhängig von der Rücksprache schon jetzt implementieren. Sollte sich dann unerwarteterweise herausstellen, dass Upstream eine andere Font als Fallback bevorzugt, ist das dann ja schnell angepasst.

Eine Rückfrage hätte zwei Ziele:
- Herausfinden, ob der Upstream bzgl. Fallback eine Präferenz hat, und falls ja, welche.
- Beim Upstream das Bewusstsein schaffen (falls nicht schon vorhanden), dass nicht alle denkbaren Vorgaben &ndash; und selbst so banal scheinende wie "Schriftart ist Arial" &ndash; sich nicht überall legal umsetzen lassen.

**Comment by stefan-ka** [comment]
> Könntest du das im README vielleicht kurz beschreiben? Den Default möchte ich schon bei Arial lassen.

@The-Compiler, kannst Du das README entsprechend mit einem Kommentar für Linux-Users erweitern wenn Du den Fallback einbaust? ;) Dann lasse ich das vorerst noch sein...

**Comment by kakila** [comment]
Ein Fallback ist ein Muss!
Warum zwingen Sie die Benutzer, ihr System mit nicht offenen Schriften zu beschmutzen? Können Sie nicht Arial-Ersetzungen wie FreeSans oder ereignisbessere Schriften wie Roboto verwenden?

**Comment by misto** [comment]
Wie gesagt, ich hätte sehr gerne einen Fallback drin, aber den müsste jemand implementieren. Pull Requests dazu nehme ich sehr gerne an, aber der Default wird weiterhin den Vorgaben des OST Corporate Designs folgen.

**Comment by The-Compiler** [comment]
Ich bin bisher noch nicht dazu gekommen - für Bsys haben wir uns (primär wegen #6) dazu entschieden, unser eigenes Template (minimal) anzupassen, so dass es nach OST statt nach HSR aussieht. Ich werd mich darum kümmern, wenn/falls wir auf dieses Template umsteigen - würde ich an sich gerne machen, aber dazu wären erstmal grössere Anpassungen nötig, für die ich die Zeit momentan nicht finde.

**Comment by das-g** [comment]
> Warum zwingen Sie die Benutzer, ihr System mit nicht offenen Schriften zu beschmutzen?

Ob die Design-Vorgaben der OST einen dazu "zwingen" (so man diese einzuhalten gedenkt) ist unklar. Das vorliegende LaTeX-Template zwingt aber niemanden zu irgendetwas, denn

- es ist ein Angebot _zusätzlich_ zu den bisher verfügbaren MS-Office-Vorlagen, das man nutzen kann, aber nicht muss
- es kann bei Bedarf schon jetzt vom Benutzer manuell so angepasst werden, dass es eine andere Schriftart verwendet

**Comment by kakila** [comment]
>     * es ist ein Angebot _zusätzlich_ zu den bisher verfügbaren MS-Office-Vorlagen, das man nutzen kann, aber nicht muss

In meiner Branche sind MS-Produktchen keine Option, wenn man produktiv sein will.
Diese Ressource erfüllt ein Grundbedürfnis! Ausgezeichnet!

**Comment by misto** [comment]
Dank @ubaumann haben wir jetzt einen Fallback von Arial auf Liberation Sans.
